Tetris Game with Raylib: RandomBlockGenerator Class Reference
RandomBlockGenerator Class Reference
Lớp hỗ trợ sinh ngẫu nhiên các khối Tetris.
#include <RandomBlockGenerator.h>
Static Public Member Functions
static std::unique_ptr< Block > Generate (int gridColumns)
Sinh ngẫu nhiên một block và đặt nó vào giữa lưới.
Detailed Description
Lớp hỗ trợ sinh ngẫu nhiên các khối Tetris.
Lớp này cung cấp phương thức tĩnh để tạo ra một block mới trong số 7 loại block chuẩn của Tetris (I, J, L, O, S, T, Z).
Definition at line 12 of file RandomBlockGenerator.h.
Member Function Documentation
Generate()
std::unique_ptr< Block > RandomBlockGenerator::Generate (int gridColumns) static
Sinh ngẫu nhiên một block và đặt nó vào giữa lưới.
Sinh ngẫu nhiên một khối (Block) trong trò chơi Tetris.
Parameters
gridColumns Số cột của lưới, dùng để xác định vị trí ban đầu của block.
Returns
std::unique_ptr<Block> Con trỏ thông minh trỏ tới block được tạo.
Hàm này sẽ chọn một khối trong số 7 loại khối Tetris (I, J, L, O, S, T, Z) dựa trên giá trị ngẫu nhiên. Khối sau khi được tạo sẽ được dịch chuyển sang vị trí giữa bảng (theo số cột).
Parameters
gridColumns Số cột của lưới (grid) trong game. Dùng để xác định vị trí ban đầu của block.
Returns
std::unique_ptr<Block> Con trỏ thông minh trỏ đến khối vừa được sinh ra.
< Đảm bảo srand chỉ khởi tạo 1 lần duy nhất
< Khởi tạo seed cho random
< Chọn ngẫu nhiên loại block (0-6)
Tạo block tương ứng với type
< Khối thẳng (I)
< Khối chữ J
< Khối chữ L
< Khối vuông (O)
< Khối chữ S
< Khối chữ T
< Khối chữ Z
< Tính cột trung tâm
< Đặt block vào vị trí giữa lưới
< Trả về block vừa tạo
Definition at line 23 of file RandomBlockGenerator.cpp.
{
    static bool initialized = false;
    if (!initialized) {
        std::srand(static_cast<unsigned>(std::time(nullptr)));
        initialized = true;
    }
    int type = std::rand() % 7;
    std::unique_ptr<Block> block;
    switch (type) {
        case 0: block = std::make_unique<IBlock>(); break;
        case 1: block = std::make_unique<JBlock>(); break;
        case 2: block = std::make_unique<LBlock>(); break;
        case 3: block = std::make_unique<OBlock>(); break;
        case 4: block = std::make_unique<SBlock>(); break;
        case 5: block = std::make_unique<TBlock>(); break;
        case 6: block = std::make_unique<ZBlock>(); break;
    }
    int center_column = gridColumns / 2;
    block->Move(0, center_column);
    return block;
}
Referenced by GameController::Init(), GameController::Reset(), and GameController::SpawnNewBlock().
The documentation for this class was generated from the following files:
Model/BlockService/RandomBlockGenerator.h
Model/BlockService/RandomBlockGenerator.cpp