Tetris Game with Raylib: Game Class Reference
Game Class Reference
Quản lý toàn bộ vòng đời và logic chính của trò chơi Tetris.
#include <game.h>
Public Member Functions
Game ()
Khởi tạo trò chơi và sinh khối đầu tiên.
~Game ()
Giải phóng bộ nhớ.
void Draw ()
Vẽ lưới, khối hiện tại và khối tiếp theo.
void HandleInput ()
Xử lý các thao tác từ người chơi như di chuyển, xoay, thả nhanh.
void MoveBlockDown ()
Di chuyển khối xuống theo thời gian.
void LoadBestScore ()
Tải điểm cao nhất từ file.
void SaveBestScore ()
Lưu điểm cao nhất vào file.
std::shared_ptr< AudioService > GetAudioService ()
Lấy AudioService hiện tại.
Public Attributes
bool gameOver
Trạng thái kết thúc trò chơi.
int score
Điểm hiện tại của người chơi.
int bestScore = 0
Điểm cao nhất trong các lần chơi.
std::shared_ptr< AudioService > audioService
Dịch vụ âm thanh dùng để phát hiệu ứng.
Private Member Functions
void MoveBlockLeft ()
Di chuyển khối sang trái nếu hợp lệ.
void MoveBlockRight ()
Di chuyển khối sang phải nếu hợp lệ.
void HardDrop ()
Thả khối xuống đáy nhanh chóng.
std::unique_ptr< Block > GetRandomBlock ()
Tạo một khối ngẫu nhiên từ danh sách khối.
std::vector< std::unique_ptr< Block > > GetAllBlocks ()
Lấy danh sách tất cả các loại khối.
bool IsBlockOutside ()
Kiểm tra xem khối hiện tại có nằm ngoài lưới không.
void RotateBlock ()
Xoay khối hiện tại nếu hợp lệ.
void LockBlock ()
Khóa khối vào lưới khi không thể di chuyển thêm.
bool BlockFits ()
Kiểm tra khối có vừa vặn trong lưới không.
void Reset ()
Reset trò chơi, khởi tạo lại trạng thái ban đầu.
void UpdateScore (int linesCleared, int moveDownPoints)
Cập nhật điểm số dựa trên số dòng bị xóa và điểm rơi khối.
Private Attributes
Grid grid
Lưới chính của trò chơi.
std::vector< std::unique_ptr< Block > > blocks
Danh sách các khối khả dụng.
std::unique_ptr< Block > currentBlock
Khối đang hoạt động hiện tại.
std::unique_ptr< Block > nextBlock
Khối tiếp theo sẽ xuất hiện sau currentBlock.
Detailed Description
Quản lý toàn bộ vòng đời và logic chính của trò chơi Tetris.
Lớp này xử lý việc tạo khối, di chuyển, xoay, tính điểm, khóa khối và kiểm tra trạng thái trò chơi. Đồng thời chịu trách nhiệm giao tiếp với dịch vụ âm thanh và vẽ màn hình.
Definition at line 22 of file game.h.
Constructor & Destructor Documentation
Game()
Game::Game ()
Khởi tạo trò chơi và sinh khối đầu tiên.
Definition at line 51 of file game.cpp.
{
    grid = Grid();
    blocks = GetAllBlocks();
    currentBlock = GetRandomBlock();
    nextBlock = GetRandomBlock();
    gameOver = false;
    score = 0;
    audioService = std::make_shared<AudioService>();
    LoadBestScore();
}
References audioService, blocks, currentBlock, gameOver, GetAllBlocks(), GetRandomBlock(), grid, LoadBestScore(), nextBlock, and score.
~Game()
Game::~Game () default
Giải phóng bộ nhớ.
Member Function Documentation
BlockFits()
bool Game::BlockFits () private
Kiểm tra khối có vừa vặn trong lưới không.
Returns
True nếu vừa.
Definition at line 255 of file game.cpp.
{
    std::vector<Position> tiles = currentBlock->GetCellPositions();
    for (Position item : tiles)
    {
        if (grid.IsCellEmpty(item.row, item.column) == false)
        {
            return false;
        }
    }
    return true;
}
References currentBlock, and grid.
Referenced by HardDrop(), LockBlock(), MoveBlockDown(), MoveBlockLeft(), MoveBlockRight(), and RotateBlock().
Draw()
void Game::Draw ()
Vẽ lưới, khối hiện tại và khối tiếp theo.
Definition at line 96 of file game.cpp.
{
    grid.Draw();
    currentBlock->Draw(11, 11);
    int boxX = 630;
    int boxY = 310;
    int boxWidth = 170;
    int boxHeight = 180;
    auto size = nextBlock->GetSize();
    int blockPixelWidth = size.first * 30;
    int blockPixelHeight = size.second * 30;
    int offsetX = boxX + (boxWidth - blockPixelWidth) / 2 - 90;
    int offsetY = boxY + (boxHeight - blockPixelHeight) / 2;
    if (nextBlock->id == 4) {
        offsetX -= 27; // Adjust for OBlock offset
    }
    nextBlock->Draw(offsetX, offsetY);
}
References currentBlock, grid, and nextBlock.
GetAllBlocks()
std::vector< std::unique_ptr< Block > > Game::GetAllBlocks () private
Lấy danh sách tất cả các loại khối.
Returns
Vector chứa các khối mẫu.
Definition at line 83 of file game.cpp.
{
    std::vector<std::unique_ptr<Block>> result;
    result.push_back(std::make_unique<IBlock>());
    result.push_back(std::make_unique<JBlock>());
    result.push_back(std::make_unique<LBlock>());
    result.push_back(std::make_unique<OBlock>());
    result.push_back(std::make_unique<SBlock>());
    result.push_back(std::make_unique<TBlock>());
    result.push_back(std::make_unique<ZBlock>());
    return result;
}
Referenced by Game(), GetRandomBlock(), and Reset().
GetAudioService()
std::shared_ptr< AudioService > Game::GetAudioService ()
Lấy AudioService hiện tại.
Returns
Shared pointer trỏ đến AudioService.
Definition at line 64 of file game.cpp.
{
    return audioService;
}
References audioService.
GetRandomBlock()
std::unique_ptr< Block > Game::GetRandomBlock () private
Tạo một khối ngẫu nhiên từ danh sách khối.
Returns
Con trỏ unique_ptr đến khối mới.
Definition at line 71 of file game.cpp.
{
    if (blocks.empty())
    {
        blocks = GetAllBlocks();
    }
    int randomIndex = rand() % blocks.size();
    std::unique_ptr<Block> block = std::move(blocks[randomIndex]);
    blocks.erase(blocks.begin() + randomIndex);
    return block;
}
References blocks, and GetAllBlocks().
Referenced by Game(), LockBlock(), and Reset().
HandleInput()
void Game::HandleInput ()
Xử lý các thao tác từ người chơi như di chuyển, xoay, thả nhanh.
Definition at line 121 of file game.cpp.
{
    int keyPressed = GetKeyPressed();
    if (gameOver && keyPressed != 0)
    {
        gameOver = false;
        Reset();
    }
    switch (keyPressed)
    {
    case KEY_LEFT:
        MoveBlockLeft();
        break;
    case KEY_RIGHT:
        MoveBlockRight();
        break;
    case KEY_DOWN:
        MoveBlockDown();
        UpdateScore(0, 1);
        break;
    case KEY_UP:
        RotateBlock();
        break;
    case KEY_SPACE:
        HardDrop();
        break;
    }
}
References gameOver, HardDrop(), MoveBlockDown(), MoveBlockLeft(), MoveBlockRight(), Reset(), RotateBlock(), and UpdateScore().
HardDrop()
void Game::HardDrop () private
Thả khối xuống đáy nhanh chóng.
Definition at line 187 of file game.cpp.
{
    if (!gameOver)
    {
        while (true)
        {
            currentBlock->Move(1, 0);
            if (IsBlockOutside() || BlockFits() == false)
            {
                currentBlock->Move(-1, 0);
                LockBlock();
                break;
            }
        }
    }
    audioService->PlayRotateSound();
}
References audioService, BlockFits(), currentBlock, gameOver, IsBlockOutside(), and LockBlock().
Referenced by HandleInput().
IsBlockOutside()
bool Game::IsBlockOutside () private
Kiểm tra xem khối hiện tại có nằm ngoài lưới không.
Returns
True nếu nằm ngoài.
Definition at line 205 of file game.cpp.
{
    std::vector<Position> tiles = currentBlock->GetCellPositions();
    for (Position item : tiles)
    {
        if (grid.IsCellOutside(item.row, item.column))
        {
            return true;
        }
    }
    return false;
}
References currentBlock, and grid.
Referenced by HardDrop(), MoveBlockDown(), MoveBlockLeft(), MoveBlockRight(), and RotateBlock().
LoadBestScore()
void Game::LoadBestScore ()
Tải điểm cao nhất từ file.
Definition at line 28 of file game.cpp.
{
    std::ifstream file(BEST_SCORE_FILE);
    if (file.is_open()) {
        file >> bestScore;
        file.close();
    } else {
        bestScore = 0;
    }
}
References BEST_SCORE_FILE, and bestScore.
Referenced by Game().
LockBlock()
void Game::LockBlock () private
Khóa khối vào lưới khi không thể di chuyển thêm.
Definition at line 234 of file game.cpp.
{
    std::vector<Position> tiles = currentBlock->GetCellPositions();
    for (Position item : tiles)
    {
        grid.grid[item.row][item.column] = currentBlock->id;
    }
    currentBlock = std::move(nextBlock);
    if (BlockFits() == false)
    {
        gameOver = true;
    }
    nextBlock = GetRandomBlock();
    int rowsCleared = grid.ClearFullRows();
    if (rowsCleared > 0)
    {
        audioService->PlayClearSound();
        UpdateScore(rowsCleared, 0);
    }
}
References audioService, BlockFits(), currentBlock, gameOver, GetRandomBlock(), grid, nextBlock, and UpdateScore().
Referenced by HardDrop(), and MoveBlockDown().
MoveBlockDown()
void Game::MoveBlockDown ()
Di chuyển khối xuống theo thời gian.
Definition at line 174 of file game.cpp.
{
    if (!gameOver)
    {
        currentBlock->Move(1, 0);
        if (IsBlockOutside() || BlockFits() == false)
        {
            currentBlock->Move(-1, 0);
            LockBlock();
        }
    }
}
References BlockFits(), currentBlock, gameOver, IsBlockOutside(), and LockBlock().
Referenced by HandleInput().
MoveBlockLeft()
void Game::MoveBlockLeft () private
Di chuyển khối sang trái nếu hợp lệ.
Definition at line 150 of file game.cpp.
{
    if (!gameOver)
    {
        currentBlock->Move(0, -1);
        if (IsBlockOutside() || BlockFits() == false)
        {
            currentBlock->Move(0, 1);
        }
    }
}
References BlockFits(), currentBlock, gameOver, and IsBlockOutside().
Referenced by HandleInput().
MoveBlockRight()
void Game::MoveBlockRight () private
Di chuyển khối sang phải nếu hợp lệ.
Definition at line 162 of file game.cpp.
{
    if (!gameOver)
    {
        currentBlock->Move(0, 1);
        if (IsBlockOutside() || BlockFits() == false)
        {
            currentBlock->Move(0, -1);
        }
    }
}
References BlockFits(), currentBlock, gameOver, and IsBlockOutside().
Referenced by HandleInput().
Reset()
void Game::Reset () private
Reset trò chơi, khởi tạo lại trạng thái ban đầu.
Definition at line 268 of file game.cpp.
{
    grid.Initialize();
    blocks = GetAllBlocks();
    currentBlock = GetRandomBlock();
    nextBlock = GetRandomBlock();
    score = 0;
}
References blocks, currentBlock, GetAllBlocks(), GetRandomBlock(), grid, nextBlock, and score.
Referenced by HandleInput().
RotateBlock()
void Game::RotateBlock () private
Xoay khối hiện tại nếu hợp lệ.
Definition at line 218 of file game.cpp.
{
    if (!gameOver)
    {
        currentBlock->Rotate();
        if (IsBlockOutside() || BlockFits() == false)
        {
            currentBlock->UndoRotation();
        }
        else
        {
            audioService->PlayRotateSound();
        }
    }
}
References audioService, BlockFits(), currentBlock, gameOver, and IsBlockOutside().
Referenced by HandleInput().
SaveBestScore()
void Game::SaveBestScore ()
Lưu điểm cao nhất vào file.
Definition at line 38 of file game.cpp.
{
    if (score > bestScore) {
        bestScore = score;
        std::ofstream file(BEST_SCORE_FILE);
        if (file.is_open()) {
            file << bestScore;
            file.close();
        } else {
            std::cerr << "Error: Can't save best score .\n";
        }
    }
}
References BEST_SCORE_FILE, bestScore, and score.
UpdateScore()
void Game::UpdateScore (int linesCleared, int moveDownPoints) private
Cập nhật điểm số dựa trên số dòng bị xóa và điểm rơi khối.
Parameters
linesCleared Số dòng đã xóa.
moveDownPoints Điểm thưởng từ việc rơi nhanh.
Definition at line 277 of file game.cpp.
{
    switch (linesCleared)
    {
    case 1:
        score += 100;
        break;
    case 2:
        score += 300;
        break;
    case 3:
        score += 500;
        break;
    default:
        break;
    }
    score += moveDownPoints;
}
References score.
Referenced by HandleInput(), and LockBlock().
Member Data Documentation
audioService
std::shared_ptr<AudioService> Game::audioService
Dịch vụ âm thanh dùng để phát hiệu ứng.
Definition at line 78 of file game.h.
Referenced by Game(), GetAudioService(), HardDrop(), LockBlock(), and RotateBlock().
bestScore
int Game::bestScore = 0
Điểm cao nhất trong các lần chơi.
Definition at line 63 of file game.h.
Referenced by LoadBestScore(), and SaveBestScore().
blocks
std::vector<std::unique_ptr<Block> > Game::blocks private
Danh sách các khối khả dụng.
Definition at line 156 of file game.h.
Referenced by Game(), GetRandomBlock(), and Reset().
currentBlock
std::unique_ptr<Block> Game::currentBlock private
Khối đang hoạt động hiện tại.
Definition at line 161 of file game.h.
Referenced by BlockFits(), Draw(), Game(), HardDrop(), IsBlockOutside(), LockBlock(), MoveBlockDown(), MoveBlockLeft(), MoveBlockRight(), Reset(), and RotateBlock().
gameOver
bool Game::gameOver
Trạng thái kết thúc trò chơi.
Definition at line 53 of file game.h.
Referenced by Game(), HandleInput(), HardDrop(), LockBlock(), MoveBlockDown(), MoveBlockLeft(), MoveBlockRight(), and RotateBlock().
grid
Grid Game::grid private
Lưới chính của trò chơi.
Definition at line 151 of file game.h.
Referenced by BlockFits(), Draw(), Game(), IsBlockOutside(), LockBlock(), and Reset().
nextBlock
std::unique_ptr<Block> Game::nextBlock private
Khối tiếp theo sẽ xuất hiện sau currentBlock.
Definition at line 166 of file game.h.
Referenced by Draw(), Game(), LockBlock(), and Reset().
score
int Game::score
Điểm hiện tại của người chơi.
Definition at line 58 of file game.h.
Referenced by Game(), Reset(), SaveBestScore(), and UpdateScore().
The documentation for this class was generated from the following files:
game/game.h
game/game.cpp