Tetris Game with Raylib: Grid Class Reference
Grid Class Reference
<
#include <Grid.h>
Public Member Functions
Grid (int rows, int columns)
Khởi tạo lưới với số hàng và cột.
bool IsCellOccupied (int row, int column) const
Kiểm tra xem ô tại (row, column) có bị chiếm không.
void SetCell (int row, int column, const Color &color)
Đặt màu cho một ô trong lưới.
void ClearCell (int row, int column)
Xóa (làm trống) một ô trong lưới.
int ClearFullLines ()
Xóa toàn bộ các dòng đầy trong lưới.
int GetRows () const
Lấy số hàng của lưới.
int GetColumns () const
Lấy số cột của lưới.
const std::vector< std::vector< Color > > & GetCells () const
Lấy toàn bộ dữ liệu các ô của lưới.
bool IsValidPosition (const std::vector< Position > &positions) const
Kiểm tra xem một tập hợp vị trí có hợp lệ trong lưới hay không.
bool HasBlockAtTop () const
Kiểm tra xem có block nào chạm đỉnh lưới không.
Private Attributes
int _rows
Số hàng.
int _columns
Số cột.
std::vector< std::vector< Color > > _cells
Ma trận cell (mỗi cell là một màu).
Detailed Description
<
<
Note
Dùng Color tự định nghĩa, không phải raylib::Color
Dùng Position tự định nghĩa, không phải raylib::Vector2
Đại diện cho lưới (bảng trò chơi) chứa các cell màu sắc.
Mỗi cell có thể rỗng hoặc chứa màu (tương ứng với khối).
Quản lý việc kiểm tra hợp lệ, xóa dòng đầy, và trạng thái lưới.
Definition at line 15 of file Grid.h.
Constructor & Destructor Documentation
Grid()
Grid::Grid (int rows, int columns)
Khởi tạo lưới với số hàng và cột.
Khởi tạo lưới game với kích thước rows × columns.
Parameters
rows Số hàng.
columns Số cột.
Tất cả ô trong lưới ban đầu đều là màu trong suốt (alpha = 0).
Parameters
rows Số hàng của lưới.
columns Số cột của lưới.
Definition at line 11 of file Grid.cpp.
    : _rows(rows), _columns(columns),
      _cells(rows, std::vector<Color>(columns, Color{0, 0, 0, 0})) {}
References _cells, _columns, and _rows.
Member Function Documentation
ClearCell()
void Grid::ClearCell (int row, int column)
Xóa (làm trống) một ô trong lưới.
Parameters
row Chỉ số hàng.
column Chỉ số cột.
Definition at line 48 of file Grid.cpp.
{
    if (row < 0 || row >= _rows || column < 0 || column >= _columns)
        return;
    _cells[row][column] = Color{0, 0, 0, 0};
}
References _cells, _columns, and _rows.
ClearFullLines()
int Grid::ClearFullLines ()
Xóa toàn bộ các dòng đầy trong lưới.
Xóa các dòng đầy trong lưới.
Returns
Số dòng đã bị xóa.
Nếu một dòng đầy (không có ô trống), dòng đó bị xóa và các dòng trên được đẩy xuống. Một dòng trống mới được chèn ở trên cùng.
Returns
int Số dòng đã xóa.
Definition at line 62 of file Grid.cpp.
{
    int cleared = 0;
    for (int row = _rows - 1; row >= 0; --row) {
        bool full = std::all_of(_cells[row].begin(), _cells[row].end(),
                                [](const Color& c) { return c.a != 0; });
        if (full) {
            // Xóa dòng đầy
            _cells.erase(_cells.begin() + row);
            // Thêm dòng trống ở trên cùng
            _cells.insert(_cells.begin(), std::vector<Color>(_columns, Color{0, 0, 0, 0}));
            ++cleared;
            ++row; // kiểm tra lại dòng vừa đẩy xuống
        }
    }
    return cleared;
}
References _cells, _columns, and _rows.
Referenced by GameLogicService::ClearLines().
GetCells()
const std::vector< std::vector< Color > > & Grid::GetCells () const
Lấy toàn bộ dữ liệu các ô của lưới.
Lấy toàn bộ dữ liệu ô trong lưới.
Returns
const std::vector<std::vector<Color>>& Ma trận màu (tham chiếu hằng).
Definition at line 105 of file Grid.cpp.
{
    return _cells;
}
References _cells.
Referenced by GridRenderer::Draw().
GetColumns()
int Grid::GetColumns () const
Lấy số cột của lưới.
Returns
int Số cột.
Definition at line 96 of file Grid.cpp.
{
    return _columns;
}
References _columns.
Referenced by GridRenderer::Draw(), and GameLogicService::LockBlock().
GetRows()
int Grid::GetRows () const
Lấy số hàng của lưới.
Returns
int Số hàng.
Definition at line 88 of file Grid.cpp.
{
    return _rows;
}
References _rows.
Referenced by GridRenderer::Draw(), and GameLogicService::LockBlock().
HasBlockAtTop()
bool Grid::HasBlockAtTop () const
Kiểm tra xem có block nào chạm đỉnh lưới không.
Returns
true nếu có block ở hàng trên cùng.
true Nếu có ô ở hàng 0 đã bị chiếm.
false Nếu chưa có ô nào ở hàng 0.
Definition at line 134 of file Grid.cpp.
{
    for (int col = 0; col < _columns; ++col) {
        if (_cells[0][col].a != 0) return true;
    }
    return false;
}
References _cells, and _columns.
Referenced by GameLogicService::IsGameOver().
IsCellOccupied()
bool Grid::IsCellOccupied (int row, int column) const
Kiểm tra xem ô tại (row, column) có bị chiếm không.
Kiểm tra ô có bị chiếm không.
Parameters
row Chỉ số hàng.
column Chỉ số cột.
Returns
true nếu bị chiếm hoặc ngoài lưới.
Parameters
row Chỉ số hàng.
column Chỉ số cột.
Returns
true Nếu ô ngoài lưới hoặc có màu (alpha ≠ 0).
false Nếu ô còn trống.
Definition at line 23 of file Grid.cpp.
{
    if (row < 0 || row >= _rows || column < 0 || column >= _columns)
        return true; // ngoài lưới xem như occupied
    return _cells[row][column].a != 0;
}
References _cells, _columns, and _rows.
Referenced by IsValidPosition().
IsValidPosition()
bool Grid::IsValidPosition (const std::vector< Position > & positions) const
Kiểm tra xem một tập hợp vị trí có hợp lệ trong lưới hay không.
Kiểm tra vị trí tập hợp các ô có hợp lệ không.
Parameters
positions Danh sách vị trí.
Returns
true nếu tất cả đều nằm trong lưới và không bị chiếm.
Hợp lệ nếu toàn bộ tọa độ đều nằm trong lưới và không đè lên ô đã chiếm.
Parameters
positions Danh sách tọa độ cần kiểm tra.
Returns
true Nếu vị trí hợp lệ.
false Nếu vị trí không hợp lệ.
Definition at line 118 of file Grid.cpp.
{
    for (const auto& pos : positions) {
        if (pos.row < 0 || pos.row >= _rows || pos.column < 0 || pos.column >= _columns)
            return false;
        if (IsCellOccupied(pos.row, pos.column))
            return false;
    }
    return true;
}
References _columns, _rows, and IsCellOccupied().
Referenced by GameLogicService::MoveDown(), GameLogicService::MoveLeft(), GameLogicService::MoveRight(), and GameLogicService::Rotate().
SetCell()
void Grid::SetCell (int row, int column, const Color & color)
Đặt màu cho một ô trong lưới.
Gán màu cho một ô trong lưới.
Parameters
row Chỉ số hàng.
column Chỉ số cột.
color Màu cần đặt.
row Chỉ số hàng.
column Chỉ số cột.
color Màu muốn gán.
Definition at line 36 of file Grid.cpp.
{
    if (row < 0 || row >= _rows || column < 0 || column >= _columns)
        return; // tránh ghi ngoài lưới
    _cells[row][column] = color;
}
References _cells, _columns, and _rows.
Referenced by GameLogicService::LockBlock().
Member Data Documentation
_cells
std::vector<std::vector<Color> > Grid::_cells private
Ma trận cell (mỗi cell là một màu).
Definition at line 78 of file Grid.h.
Referenced by ClearCell(), ClearFullLines(), GetCells(), Grid(), HasBlockAtTop(), IsCellOccupied(), and SetCell().
_columns
int Grid::_columns private
Số cột.
Definition at line 77 of file Grid.h.
Referenced by ClearCell(), ClearFullLines(), GetColumns(), Grid(), HasBlockAtTop(), IsCellOccupied(), IsValidPosition(), and SetCell().
_rows
int Grid::_rows private
Số hàng.
Definition at line 76 of file Grid.h.
Referenced by ClearCell(), ClearFullLines(), GetRows(), Grid(), IsCellOccupied(), IsValidPosition(), and SetCell().
The documentation for this class was generated from the following files:
Core/Grid/Grid.h
Core/Grid/Grid.cpp