Tetris Game with Raylib: GameLogicService Class Reference
GameLogicService Class Reference
Cung cấp các hàm xử lý logic chính cho trò chơi Tetris.
#include <GameLogicService.h>
Public Member Functions
bool MoveLeft (Block &block, const Grid &grid) const
Di chuyển block sang trái.
bool MoveRight (Block &block, const Grid &grid) const
Di chuyển block sang phải.
bool MoveDown (Block &block, const Grid &grid) const
Di chuyển block xuống dưới.
bool Rotate (Block &block, const Grid &grid) const
Xoay block (theo chiều kim đồng hồ).
void LockBlock (Grid &grid, const Block &block) const
Khóa block vào grid khi block chạm đáy hoặc bị cản.
int ClearLines (Grid &grid) const
Xóa các dòng đầy đủ trong grid.
bool IsGameOver (const Grid &grid) const
Kiểm tra game có kết thúc hay chưa.
Detailed Description
Cung cấp các hàm xử lý logic chính cho trò chơi Tetris.
Lớp này quản lý việc di chuyển, xoay, khóa block vào grid, kiểm tra xóa dòng, và xác định trạng thái game over.
Definition at line 14 of file GameLogicService.h.
Member Function Documentation
ClearLines()
int GameLogicService::ClearLines (Grid & grid) const
Xóa các dòng đầy đủ trong grid.
Xóa các hàng đầy trong lưới.
Parameters
grid Lưới cần kiểm tra.
Returns
Số dòng đã xóa.
Parameters
grid Lưới trò chơi cần xử lý.
Returns
int Số hàng đã xóa.
Definition at line 109 of file GameLogicService.cpp.
{
    return grid.ClearFullLines();
}
References Grid::ClearFullLines().
IsGameOver()
bool GameLogicService::IsGameOver (const Grid & grid) const
Kiểm tra game có kết thúc hay chưa.
Kiểm tra trò chơi có kết thúc hay chưa.
Parameters
grid Lưới để kiểm tra.
Returns
true nếu game over, false nếu vẫn chơi tiếp.
Parameters
grid Lưới trò chơi.
Returns
true Nếu có block xuất hiện ở hàng trên cùng (game over).
false Nếu trò chơi vẫn tiếp tục.
Definition at line 120 of file GameLogicService.cpp.
{
    return grid.HasBlockAtTop();
}
References Grid::HasBlockAtTop().
LockBlock()
void GameLogicService::LockBlock (Grid & grid, const Block & block) const
Khóa block vào grid khi block chạm đáy hoặc bị cản.
Khóa block vào lưới (sau khi block chạm đáy hoặc khối khác).
Parameters
grid Lưới để cập nhật trạng thái.
block Block cần được khóa.
grid Lưới trò chơi để cập nhật cell.
block Khối cần được cố định vào grid.
Exceptions
std::runtime_error Nếu số lượng cell và số lượng màu không khớp.
Definition at line 78 of file GameLogicService.cpp.
{
    const auto& positions = block.GetCellPositions();
    std::vector<Color> colors = block.GetCellColor();
    // Nếu chỉ có 1 màu, nhân bản màu để match số cell
    if (colors.size() == 1 && positions.size() > 1) {
        colors = std::vector<Color>(positions.size(), colors[0]);
    }
    // Nếu mismatch, throw để phát hiện lỗi sớm
    if (positions.size() != colors.size()) {
        throw std::runtime_error("LockBlock error: positions.size() != colors.size()");
    }
    for (size_t i = 0; i < positions.size(); ++i) {
        const auto& pos = positions[i];
        if (pos.row >= 0 && pos.row < grid.GetRows() &&
            pos.column >= 0 && pos.column < grid.GetColumns()) {
            grid.SetCell(pos.row, pos.column, colors[i]);
        } else {
            // Log hoặc bỏ qua nếu vị trí ngoài grid
        }
    }
}
References Block::GetCellColor(), Block::GetCellPositions(), Grid::GetColumns(), Grid::GetRows(), and Grid::SetCell().
MoveDown()
bool GameLogicService::MoveDown (Block & block, const Grid & grid) const
Di chuyển block xuống dưới.
Di chuyển block xuống một hàng nếu có thể.
Parameters
block Block cần di chuyển.
grid Lưới để kiểm tra va chạm.
Returns
true nếu di chuyển thành công, false nếu bị cản.
Parameters
block Khối Tetris cần di chuyển.
grid Lưới trò chơi dùng để kiểm tra va chạm.
Returns
true Nếu di chuyển thành công.
false Nếu block chạm đáy hoặc block khác (block sẽ trở lại vị trí cũ).
Definition at line 45 of file GameLogicService.cpp.
{
    block.MoveDown();
    if (!grid.IsValidPosition(block.GetCellPositions())) {
        block.MoveUp();
        return false;
    }
    return true;
}
References Block::GetCellPositions(), Grid::IsValidPosition(), Block::MoveDown(), and Block::MoveUp().
MoveLeft()
bool GameLogicService::MoveLeft (Block & block, const Grid & grid) const
Di chuyển block sang trái.
Di chuyển block sang trái nếu có thể.
Parameters
block Block cần di chuyển.
grid Lưới để kiểm tra va chạm.
Returns
true nếu di chuyển thành công, false nếu bị cản.
Parameters
block Khối Tetris cần di chuyển.
grid Lưới trò chơi dùng để kiểm tra va chạm.
Returns
true Nếu di chuyển thành công.
false Nếu không thể di chuyển (block sẽ trở lại vị trí cũ).
Definition at line 11 of file GameLogicService.cpp.
{
    block.MoveLeft();
    if (!grid.IsValidPosition(block.GetCellPositions())) {
        block.MoveRight();
        return false;
    }
    return true;
}
References Block::GetCellPositions(), Grid::IsValidPosition(), Block::MoveLeft(), and Block::MoveRight().
MoveRight()
bool GameLogicService::MoveRight (Block & block, const Grid & grid) const
Di chuyển block sang phải.
Di chuyển block sang phải nếu có thể.
Parameters
block Block cần di chuyển.
grid Lưới để kiểm tra va chạm.
Returns
true nếu di chuyển thành công, false nếu bị cản.
Parameters
block Khối Tetris cần di chuyển.
grid Lưới trò chơi dùng để kiểm tra va chạm.
Returns
true Nếu di chuyển thành công.
false Nếu không thể di chuyển (block sẽ trở lại vị trí cũ).
Definition at line 28 of file GameLogicService.cpp.
{
    block.MoveRight();
    if (!grid.IsValidPosition(block.GetCellPositions())) {
        block.MoveLeft();
        return false;
    }
    return true;
}
References Block::GetCellPositions(), Grid::IsValidPosition(), Block::MoveLeft(), and Block::MoveRight().
Rotate()
bool GameLogicService::Rotate (Block & block, const Grid & grid) const
Xoay block (theo chiều kim đồng hồ).
Xoay block nếu có thể.
Parameters
block Block cần xoay.
grid Lưới để kiểm tra va chạm.
Returns
true nếu xoay thành công, false nếu bị cản.
Parameters
block Khối Tetris cần xoay.
grid Lưới trò chơi dùng để kiểm tra va chạm.
Returns
true Nếu xoay thành công.
false Nếu không thể xoay (block sẽ trở lại trạng thái cũ).
Definition at line 62 of file GameLogicService.cpp.
{
    block.Rotate();
    if (!grid.IsValidPosition(block.GetCellPositions())) {
        block.RotateBack();
        return false;
    }
    return true;
}
References Block::GetCellPositions(), Grid::IsValidPosition(), Block::Rotate(), and Block::RotateBack().
The documentation for this class was generated from the following files:
Model/Game/GameLogicService.h
Model/Game/GameLogicService.cpp