Tetris Game with Raylib: App Class Reference
App Class Reference
Lớp đại diện cho toàn bộ ứng dụng, chịu trách nhiệm khởi động và điều phối trò chơi.
#include <app.h>
Public Member Functions
void Run ()
Chạy ứng dụng chính, khởi động vòng lặp game.
Detailed Description
Lớp đại diện cho toàn bộ ứng dụng, chịu trách nhiệm khởi động và điều phối trò chơi.
Lớp này thường là nơi khởi tạo cửa sổ, vòng lặp game chính và gọi các thành phần phụ như Game, UI, Audio.
Definition at line 14 of file app.h.
Member Function Documentation
Run()
void App::Run ()
Chạy ứng dụng chính, khởi động vòng lặp game.
Chạy vòng lặp chính của ứng dụng Tetris.
Khởi tạo cửa sổ, font chữ và game. Điều khiển vòng lặp chính của game, xử lý input, update logic và render toàn bộ nội dung.
Definition at line 39 of file app.cpp.
{
    InitWindow(960, 1080, "Tetris Game (OOP)");
    SetTargetFPS(60);
    // Tải font tuỳ chỉnh
    Font font = LoadFontEx("assets/font/PressStart2P-Regular.ttf", 64, 0, 0);
    std::unique_ptr<Game> game = std::make_unique<Game>();
    game->GetAudioService()->PlayMusic();
    while (!WindowShouldClose())
    {
        // Cập nhật nhạc nền
        UpdateMusicStream(game->GetAudioService()->GetMusic());
        // Xử lý input
        game->HandleInput();
        // Di chuyển khối xuống mỗi 0.2 giây
        if (EventTriggered(0.2))
        {
            game->MoveBlockDown();
        }
        // Bắt đầu vẽ
        BeginDrawing();
        ClearBackground(darkBlue);
        // Hiển thị điểm cao nhất
        DrawTextEx(font, "BEST",
            {panelX + (panelWidth - MeasureTextEx(font, "BEST", 28, 2).x) / 2, 30}, 28, 2, GOLD);
        DrawTextEx(font, "SCORE",
            {panelX + (panelWidth - MeasureTextEx(font, "SCORE", 28, 2).x) / 2, 60}, 28, 2, GOLD);
        DrawRectangleRounded({panelX, 90, panelWidth, 60}, 0.3f, 6, lightBlue);
        char bestScoreText[10];
        sprintf_s(bestScoreText, sizeof(bestScoreText), "%d", game->bestScore);
        Vector2 bestScoreSize = MeasureTextEx(font, bestScoreText, 38, 2);
        DrawTextEx(font, bestScoreText,
            {panelX + (panelWidth - bestScoreSize.x) / 2, 100}, 38, 2, WHITE);
        // Hiển thị điểm hiện tại
        DrawTextEx(font, "SCORE",
            {panelX + (panelWidth - MeasureTextEx(font, "SCORE", 28, 2).x) / 2, 170}, 28, 2, WHITE);
        DrawRectangleRounded({panelX, 200, panelWidth, 60}, 0.3f, 6, lightBlue);
        char scoreText[10];
        sprintf_s(scoreText, sizeof(scoreText), "%d", game->score);
        Vector2 scoreSize = MeasureTextEx(font, scoreText, 38, 2);
        DrawTextEx(font, scoreText,
            {panelX + (panelWidth - scoreSize.x) / 2, 210}, 38, 2, WHITE);
        // Hiển thị khối kế tiếp
        DrawTextEx(font, "NEXT",
            {panelX + (panelWidth - MeasureTextEx(font, "NEXT", 28, 2).x) / 2, 280}, 28, 2, WHITE);
        DrawRectangleRounded({panelX, 310, panelWidth, 180}, 0.3f, 6, lightBlue);
        // Hiển thị thông báo Game Over
        if (game->gameOver)
        {
            DrawTextEx(font, "GAME OVER", {400, 600}, 38, 2, WHITE);
            game->SaveBestScore();
        }
        // Vẽ lưới và các khối
        game->Draw();
        // Vẽ hướng dẫn chơi
        DrawGuide(font);
        EndDrawing();
    }
    // Đóng cửa sổ khi vòng lặp kết thúc
    CloseWindow();
}
References darkBlue, DrawGuide(), EventTriggered(), lightBlue, panelWidth, and panelX.
Referenced by main().
The documentation for this class was generated from the following files:
app/app.h
app/app.cpp