Tetris Game with Raylib: BlockFactory Class Reference
BlockFactory Class Reference
Factory pattern để tạo các khối (Block) trong game Tetris.
#include <BlockFactory.h>
Public Member Functions
BlockFactory ()
Khởi tạo BlockFactory và nạp các prototype block.
std::unique_ptr< Block > CreateBlock (int id) const
Tạo block dựa theo ID.
std::unique_ptr< Block > CreateRandomBlock () const
Tạo block ngẫu nhiên (0–6).
Private Member Functions
int GenerateRandomId () const
Sinh ngẫu nhiên ID block từ 0–6.
Private Attributes
std::array< std::unique_ptr< Block >, 7 > _prototypes
Danh sách prototype cho 7 loại block.
Detailed Description
Factory pattern để tạo các khối (Block) trong game Tetris.
Lớp này lưu trữ các prototype (I, J, L, O, S, T, Z) và cung cấp phương thức để tạo ra block theo ID hoặc ngẫu nhiên.
Definition at line 21 of file BlockFactory.h.
Constructor & Destructor Documentation
BlockFactory()
BlockFactory::BlockFactory ()
Khởi tạo BlockFactory và nạp các prototype block.
Khởi tạo BlockFactory với các prototype của 7 loại khối Tetris.
Các khối được lưu trữ dưới dạng unique_ptr để đảm bảo quản lý tài nguyên an toàn.
Definition at line 8 of file BlockFactory.cpp.
{
    _prototypes[0] = std::make_unique<IBlock>();
    _prototypes[1] = std::make_unique<JBlock>();
    _prototypes[2] = std::make_unique<LBlock>();
    _prototypes[3] = std::make_unique<OBlock>();
    _prototypes[4] = std::make_unique<SBlock>();
    _prototypes[5] = std::make_unique<TBlock>();
    _prototypes[6] = std::make_unique<ZBlock>();
}
References _prototypes.
Member Function Documentation
CreateBlock()
std::unique_ptr< Block > BlockFactory::CreateBlock (int id) const
Tạo block dựa theo ID.
Tạo một khối Tetris dựa trên ID.
Parameters
id Giá trị từ 0–6 (0: I, 1: J, 2: L, 3: O, 4: S, 5: T, 6: Z).
Returns
std::unique_ptr<Block> Con trỏ thông minh quản lý block mới tạo.
Exceptions
std::out_of_range nếu ID không hợp lệ.
std::runtime_error nếu việc clone thất bại.
Parameters
id ID của khối (0–6, tương ứng với I, J, L, O, S, T, Z).
Returns
std::unique_ptr<Block> Con trỏ thông minh tới khối được tạo.
Exceptions
std::out_of_range Nếu ID không hợp lệ.
std::runtime_error Nếu clone thất bại.
Definition at line 26 of file BlockFactory.cpp.
{
    if (id < 0 || id >= static_cast<int>(_prototypes.size())) {
        throw std::out_of_range("Invalid Block ID: " + std::to_string(id));
    }
    auto clone = _prototypes[id]->Clone();
    if (!clone) {
        throw std::runtime_error("Failed to clone Block with ID: " + std::to_string(id));
    }
    return clone;
}
References _prototypes.
Referenced by CreateRandomBlock().
CreateRandomBlock()
std::unique_ptr< Block > BlockFactory::CreateRandomBlock () const
Tạo block ngẫu nhiên (0–6).
Tạo một khối Tetris ngẫu nhiên.
Returns
std::unique_ptr<Block> Con trỏ thông minh quản lý block ngẫu nhiên.
std::unique_ptr<Block> Con trỏ thông minh tới khối ngẫu nhiên.
Definition at line 44 of file BlockFactory.cpp.
{
    return CreateBlock(GenerateRandomId());
}
References CreateBlock(), and GenerateRandomId().
GenerateRandomId()
int BlockFactory::GenerateRandomId () const private
Sinh ngẫu nhiên ID block từ 0–6.
Sinh ID ngẫu nhiên trong khoảng 0–6.
Returns
int ID block.
int ID khối ngẫu nhiên.
Definition at line 53 of file BlockFactory.cpp.
{
    static std::random_device rd;
    static std::mt19937 gen(rd());
    static std::uniform_int_distribution<> dist(0, 6);
    return dist(gen);
}
Referenced by CreateRandomBlock().
Member Data Documentation
_prototypes
std::array<std::unique_ptr<Block>, 7> BlockFactory::_prototypes private
Danh sách prototype cho 7 loại block.
Definition at line 47 of file BlockFactory.h.
Referenced by BlockFactory(), and CreateBlock().
The documentation for this class was generated from the following files:
Model/BlockService/BlockFactory.h
Model/BlockService/BlockFactory.cpp