Tetris Game with Raylib: GridRenderer Class Reference
GridRenderer Class Reference
Lớp chịu trách nhiệm hiển thị lưới (grid) và các ô chứa block.
#include <GridRender.h>
Public Member Functions
GridRenderer (int cellSize)
Khởi tạo GridRenderer với kích thước của mỗi ô.
void Draw (const Grid &grid, int offset_x, int offset_y) const
Vẽ lưới và các block từ grid lên màn hình.
Private Attributes
int _cellSize
Kích thước (pixel) của mỗi ô trong lưới.
Detailed Description
Lớp chịu trách nhiệm hiển thị lưới (grid) và các ô chứa block.
Lớp này đảm nhiệm vai trò "View" trong mô hình MVC, chỉ phụ trách phần hiển thị, không xử lý logic của game. Nó sẽ vẽ:
Đường viền lưới với màu xám nhạt.
Các ô block đã được tô màu trong grid.
Definition at line 15 of file GridRender.h.
Constructor & Destructor Documentation
GridRenderer()
GridRenderer::GridRenderer (int cellSize)
Khởi tạo GridRenderer với kích thước của mỗi ô.
Khởi tạo đối tượng GridRenderer với kích thước ô (cell size).
Parameters
cellSize Kích thước (pixel) của mỗi ô trong lưới.
cellSize Kích thước của mỗi ô trong lưới (pixel).
Definition at line 8 of file GridRender.cpp.
    : _cellSize(cellSize) {}
References _cellSize.
Member Function Documentation
Draw()
void GridRenderer::Draw (const Grid & grid, int offset_x, int offset_y) const
Vẽ lưới và các block từ grid lên màn hình.
Vẽ lưới và các ô màu của grid lên màn hình.
Parameters
grid Lưới hiện tại của game (bao gồm thông tin các ô).
offset_x Tọa độ dịch chuyển theo trục X (pixel).
offset_y Tọa độ dịch chuyển theo trục Y (pixel).
Hàm này hiển thị:
Các đường viền lưới bằng màu xám nhạt (có alpha để hiển thị mờ).
Các ô đã có block (cell có màu, alpha khác 0).
Parameters
grid Lưới game hiện tại.
offset_x Vị trí dịch theo trục X (pixel).
offset_y Vị trí dịch theo trục Y (pixel).
Definition at line 22 of file GridRender.cpp.
{
    // Màu xám nhạt có alpha để hiển thị mờ
    Color faintGray = {100, 100, 100, 50};  // R, G, B, A
    for (int row = 0; row < grid.GetRows(); ++row) {
        for (int col = 0; col < grid.GetColumns(); ++col) {
            Color cellColor = grid.GetCells()[row][col];
            // Vẽ lưới cho mọi ô
            DrawRectangleLines(
                offset_x + col * _cellSize,
                offset_y + row * _cellSize,
                _cellSize,
                _cellSize,
                faintGray
            );
            // Nếu ô có màu (có block), thì vẽ ô đó
            if (cellColor.a != 0) {
                DrawRectangle(
                    offset_x + col * _cellSize + 1,
                    offset_y + row * _cellSize + 1,
                    _cellSize - 2,
                    _cellSize - 2,
                    cellColor
                );
            }
        }
    }
}
References _cellSize, Grid::GetCells(), Grid::GetColumns(), and Grid::GetRows().
Member Data Documentation
_cellSize
int GridRenderer::_cellSize private
Kích thước (pixel) của mỗi ô trong lưới.
Definition at line 34 of file GridRender.h.
Referenced by Draw(), and GridRenderer().
The documentation for this class was generated from the following files:
View/Grid/GridRender.h
View/Grid/GridRender.cpp