Tetris Game with Raylib: Position Struct Reference
Position Struct Reference
Đại diện cho một vị trí trong lưới trò chơi bằng chỉ số hàng và cột.
#include <Position.h>
Public Member Functions
Position (int row=0, int column=0)
Khởi tạo một vị trí.
bool operator== (const Position &other) const
So sánh bằng giữa hai vị trí.
bool operator!= (const Position &other) const
So sánh khác nhau giữa hai vị trí.
Public Attributes
int row
Chỉ số hàng trong lưới.
int column
Chỉ số cột trong lưới.
Friends
std::ostream & operator<< (std::ostream &os, const Position &pos)
Xuất vị trí ra luồng dưới dạng (row, column).
Detailed Description
Đại diện cho một vị trí trong lưới trò chơi bằng chỉ số hàng và cột.
Definition at line 9 of file Position.h.
Constructor & Destructor Documentation
Position()
Position::Position (int row = 0, int column = 0)
Khởi tạo một vị trí.
Khởi tạo một vị trí với hàng và cột.
Parameters
row Chỉ số hàng (mặc định = 0).
column Chỉ số cột (mặc định = 0).
row Chỉ số hàng.
column Chỉ số cột.
Definition at line 8 of file Position.cpp.
    : row(row), column(column) {}
References column, and row.
Referenced by operator!=(), operator<<, and operator==().
Member Function Documentation
operator!=()
bool Position::operator!= (const Position & other) const
So sánh khác nhau giữa hai vị trí.
Parameters
other Vị trí cần so sánh.
Returns
true nếu khác hàng hoặc khác cột.
Definition at line 25 of file Position.cpp.
{
    return !(*this == other);
}
References Position().
operator==()
bool Position::operator== (const Position & other) const
So sánh bằng giữa hai vị trí.
Parameters
other Vị trí cần so sánh.
Returns
true nếu cùng hàng và cùng cột.
Definition at line 16 of file Position.cpp.
{
    return row == other.row && column == other.column;
}
References column, Position(), and row.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const Position & pos) friend
Xuất vị trí ra luồng dưới dạng (row, column).
Parameters
os Luồng xuất (output stream).
pos Vị trí cần in.
Returns
Tham chiếu tới luồng đã ghi.
Definition at line 35 of file Position.cpp.
{
    return os << "(" << pos.row << ", " << pos.column << ")";
}
References column, Position(), and row.
Member Data Documentation
column
int Position::column
Chỉ số cột trong lưới.
Definition at line 11 of file Position.h.
Referenced by operator<<, operator==(), and Position().
row
int Position::row
Chỉ số hàng trong lưới.
Definition at line 10 of file Position.h.
Referenced by operator<<, operator==(), and Position().
The documentation for this struct was generated from the following files:
Core/Position/Position.h
Core/Position/Position.cpp